dist: trusty
sudo: required

node_js: 8

cache:
  directories:
    - ~/.npm
install:
  - npm install

script:
  - cd modules/video && npm install && cd ../../
  - cd dride-ws && npm install && cd ../
  - mkdir dride
  - mkdir dride/thumb
  - mkdir dride/clip
  - npm run test
notifications:
  email:
    - yossi@dride.io
node_js:
  - '8'

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
